name = "dawnbird"
main = "src/index.js"
compatibility_date = "2026-06-07"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "DOCS_KV"
id = "154a91336bcd413bb5f63171a3363d34"
